trigger:
- main
- day11-azure-container-registry

pool:
  vmImage: ubuntu-latest

variables:
  imageName: day10-nginx
  tag: latest
  acrName: tarundevopsacr
  acrLoginServer: tarundevopsacr.azurecr.io

steps:
# Step 1: Checkout repo
- checkout: self
  clean: true

# Step 2: Build and push Docker image to ACR
- task: Docker@2
  displayName: Build and Push Docker Image to ACR
  inputs:
    containerRegistry: 'tarundevopsacr-service-connection-new'   # 👈 NEW service connection name
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/day10-docker-basics/Dockerfile'
    tags: |
      $(tag)

# Step 3: Verify image in ACR
- script: |
    echo "Listing images in ACR..."
    az acr repository list --name $(acrName) --output table
  displayName: 'Verify ACR Image'
