name: Terraform CI/CD
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform-iac/day6-multi-vm
    env:
      TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_ssh_public_key }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Terraform (manual method)
        run: |
          sudo apt-get update && sudo apt-get install -y unzip curl
          curl -fsSL https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip -o terraform.zip
          sudo unzip -o -q terraform.zip -d /usr/local/bin/
          terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply (manual trigger only)
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve
